name: Build and Publish .NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Используем GitHub Action для клонирования репозитория

      - name: Set up .NET
        uses: actions/setup-dotnet@v2  # Используем GitHub Action для установки .NET
        with:
          dotnet-version: '8.0'  # Укажите нужную версию .NET

      - name: Restore dependencies
        run: dotnet restore  # Запускаем команду для восстановления зависимостей

      - name: Build project
        run: dotnet build -c Release  # Запускаем команду для сборки проекта

      - name: Publish project
        run: dotnet publish -c Release -r win-x64 --self-contained  # Запускаем команду для публикации проекта

      - name: Upload published files as an artifact
        uses: actions/upload-artifact@v2  # Используем GitHub Action для загрузки артефактов
        with:
          name: published-files
          path: bin/Release/net8.0/win-x64/publish/  # Указываем путь к опубликованным файлам
